### ISSUE TITLE
Information on using WinUI with C++/WinRT is extremely unclear/nonexistent. #90 

### ISSUE THREAD

**Issue by JosephClampett** [MicrosoftDocs/winrt-related#91] opened 2019-01-24 15:11 UTC
There is no guidelines and simply installing it with the "Blank Project" template provided by the WinRT NuGet package does not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09e77fe7-6970-8c3b-09f9-47986e2010c2
* Version Independent ID: 25715011-c3c8-ce15-a1fc-db2bd62a58cf
* Content: [Getting started with the Windows UI library - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/toolkits/winui/getting-started)
* Content Source: [winrt-related-src/toolkits/winui/getting-started.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/toolkits/winui/getting-started.md)
* Product: **uwp**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment] 2019-01-25 17:25
@JosephClampett how is it not working? Are you getting an error message when you compile? 
@jesbis, are there any known issues with using WInUI with a blank C++/WinRT project? Adding @stevewhims for awareness.

**Comment by jevansaks** [comment] 2019-01-25 17:58
I haven't tried it personally but the MSDN docs seem to indicate that it's somewhat automatic in the project templates. Try this? https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/consume-apis#if-the-api-is-implemented-in-a-windows-runtime-component

If it doesn't work, you can contact the cppwinrt tool owners at http://github.com/Microsoft/xlang.

**Comment by JosephClampett** [comment] 2019-01-25 18:52
It does look like it should be automatic, but I think the docs are maybe missing a step for C++/WinRT? Installing the NuGet package, adding the suggested Xaml snippet to the `<Application/>` page, adding the `xmlns:controls="using:Microsoft.UI.Xaml.Controls"`, and compiling leads to this:
![image](https://user-images.githubusercontent.com/44207359/51765927-327a1680-20a7-11e9-869c-b2a5113eb167.png), which was in xamltypeinfo.g.cpp. The fact that this is in autogenerated code leads me to think that there's simply a step in the guide missing. If not, and it's just an issue with my IDE/computer/program specifically then I apologize.

**Comment by stevewhims** [comment] 2019-01-25 21:04
Hi, @JosephClampett, you're right that the topic doesn't cover the C++/WinRT case, but here's some info below that will hopefully unblock you. I'll go ahead now and add this info to the topic; that might be live within 24 hours, but by Monday at the latest.

So, when you add a NuGet package to a C++/WinRT project, the tooling generates a set of projection headers in your project's \Generated Files\winrt folder. To bring those headers files into your project, so that references to those new types resolve, you can go into your pch.h file and include them (here's what you'd do to include them all for the Microsoft.UI.Xaml package.

// pch.h
...
#include "winrt/Microsoft.UI.Xaml.Automation.Peers.h"
#include "winrt/Microsoft.UI.Xaml.Controls.Primitives.h"
#include "winrt/Microsoft.UI.Xaml.Media.h"
#include "winrt/Microsoft.UI.Xaml.XamlTypeInfo.h"

Thanks for filing this issue, and for helping us improve the docs.
~Steve

**Comment by JosephClampett** [comment] 2019-01-25 21:12
Oh my gosh. I... I'm so sorry. I tried for so long to `#include` the libraries and Intellisense never showed anything. I have no idea what I did wrong or what changed but it does work now. Thank for your help and I'm sorry for nothing you. The Microsoft Docs team is the best!

**Comment by JosephClampett** [comment] 2019-01-25 21:17
Oh, and you don't need to update the wiki. I guess this was just a weird, personal issue; the headers *are* obvious and the docs probably don't need any more information.

**Comment by stevewhims** [comment] 2019-01-25 21:43
Thanks, @JosephClampett, in this case I do feel like the ROI of adding this little bit of extra info to the topic is sound. :)

**Comment by JosephClampett** [comment] 2019-01-25 21:51
Oh, of course. You guys are the ones who work on the docs team. One other suggestion I have, though I'm not really sure if there's a place for this: maybe document how C++ XAML code is generated/how to control it? For example, despite the fact that I now have the WinUI headers my XAML pages are still trying to generate code with the Windows::... UI files and I don't really know where to go to fix it. That might be something to put on the VSIX page on the Visual Studio Extensions site or maybe on a "converting" page on here?

**Comment by stevewhims** [comment] 2019-01-25 21:59
Can you add more detail to this "my XAML pages are still trying to generate code with the Windows::... UI files"? I'm not able to visualize what the problem is, yet. It'd help me if you could outline the steps you're taking, and what you expect to happen (and what actually is happening, if different), and I'll see whether I can contribute any ideas. Thanks! :) ~Steve

**Comment by JosephClampett** [comment] 2019-01-25 22:21
My pch.h originally had
`#include "winrt/Windows.ApplicationModel.Activation.h"
#include "winrt/Windows.UI.Core.h"
#include "winrt/Windows.UI.Input.h"
#include "winrt/Windows.UI.Xaml.h"
#include "winrt/Windows.UI.Xaml.Controls.h"
#include "winrt/Windows.UI.Xaml.Controls.Primitives.h"
#include "winrt/Windows.UI.Xaml.Data.h"
#include "winrt/Windows.UI.Xaml.Input.h"
#include "winrt/Windows.UI.Xaml.Interop.h"
#include "winrt/Windows.UI.Xaml.Markup.h"
#include "winrt/Windows.UI.Xaml.Media.h"
#include "winrt/Windows.UI.Xaml.Navigation.h"
#include "winrt/Windows.UI.Xaml.Shapes.h"`

and then I replaced it with 

`#include "winrt/Windows.ApplicationModel.Activation.h"
#include "winrt/Microsoft.UI.Xaml.Controls.h"
#include "winrt/Microsoft.UI.Xaml.Media.h"
#include "winrt/Microsoft.UI.Xaml.XamlTypeInfo.h"`. Upon compiling, I get errors from all of the auto-generated code blocks for each of my controls in my XAML files. This one is for my main page, MainPage.xaml.
![image](https://user-images.githubusercontent.com/44207359/51775976-74b25080-20c5-11e9-8808-3a55c1c82c09.png)

I guess the ideal result is things like 

`        ::winrt::Windows::UI::Xaml::Controls::MenuBar MenuBar()
        {
            return _MenuBar;
        }
`

becoming 

`
        ::winrt::Microsoft::UI::Xaml::Controls::MenuBar MenuBar()
        {
            return _MenuBar;
        }
`.

**Comment by stevewhims** [comment] 2019-01-25 23:11
Hi, @JosephClampett, just as an aside, removing those #includes works because the WinUI headers include them. I think I'd be inclined to leave at least `#include <winrt/Windows.UI.Xaml.Controls.h>` in there for the W.U.X.C.Page that your XAML page derives from. Oh, and note that since the platform headers are outside of your project, you can (possibly only slightly) speed up compiles by using the angle bracket notation. The quote notation is still appropriate for the WinUI headers (and your own headers), since they're inside the project.

So, in terms of the issue you mention, let's take that MenuBar data member for example. If you add this to your XAML markup

```xaml
<MenuBar x:Name="MyPlatformMenuBar"/>
```

Then you'll get these accessors generated for that, since there is a MenuBar type in the platform in Windows::UI::Xaml::Controls.

```cppwinrt
        ::winrt::Windows::UI::Xaml::Controls::MenuBar MyPlatformMenuBar()
        {
            return _MyPlatformMenuBar;
        }
        void MyPlatformMenuBar(::winrt::Windows::UI::Xaml::Controls::MenuBar value)
        {
            _MyPlatformMenuBar = value;
        }
```

If in your XAML you have this.

```xaml
<controls:MenuBar x:Name="MyWinUIMenuBar"/>
```

Then that's explicitly using the MenuBar from the controls xmlns which, in the topic, we map to the WinUI namespace Microsoft::<etc>. So your accessors will look like this.

```cppwinrt
        ::winrt::Microsoft::UI::Xaml::Controls::MenuBar MyWinUIMenuBar()
        {
            return _MyWinUIMenuBar;
        }
        void MyWinUIMenuBar(::winrt::Microsoft::UI::Xaml::Controls::MenuBar value)
        {
            _MyWinUIMenuBar = value;
        }
```

I don't know whether that unblocks you. Please let me know.

**Comment by JosephClampett** [comment] 2019-01-26 00:07
Agh, duh. I'm sorry. That one is on incompetence (more explicitly than the last one). While it does technically work, ![image](https://user-images.githubusercontent.com/44207359/51779305-76cfdb80-20d4-11e9-8434-77a692ea7d7f.png), Intellisense can't recognize that it does and a full rebuild is forced every time. Oh, and I know that technically I'm not using the WinUI version but Intellisense bluelines the `controls:` (WinUI) versions, too. It's just a pain to add `controls:` to everything and given it's not what I would consider a working state yet I didn't bother putting it on everything.

**Comment by stevewhims** [comment] 2019-01-26 00:24
In terms of the content of the docs, I think we're resolved for this issue. So I'l go ahead and close it. But feel free to reopen, anyone on the thread, for more discussion/detail/whatnot. :) Thanks! Steve

**Closed as completed by stevewhims** 2019-01-26 00:24 UTC
