### ISSUE TITLE
Clarify usage of ref parameters in MIDL3

### ISSUE THREAD

**Issue by AliveDevil** [MicrosoftDocs/winrt-related#149] opened 2019-10-10 14:08 UTC
How are we supposed to resolve this:
```
MIDL4035	[msg]The [in] parameter has a pointer type that is not valid. [context]: Argument [ Parameter 'arg' of Procedure 'Handle' ( Interface 'IHandler' ) ]
```

Following is the definition of IHandler and Argument struct in MIDL3:
```
struct Argument
{
	Int32 Something;
};
interface IHandler
{
	void Handle(ref Argument arg);
};
```

This is necessary as I want to use the ref-parameter as "in" in a C#-project using the projection.
Following should be the definition in C#:
```
interface IHandler
{
	void Handle(in Argument arg);
}
```
Declaring the interface this way in a C# WinRT component does work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3a66bde-e2d3-c8f9-1818-711aa502c063
* Version Independent ID: 95673030-90b8-601c-8f82-dbf29357f538
* Content: [Troubleshooting Microsoft Interface Definition Language 3.0 issues - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/midl-3/troubleshooting)
* Content Source: [winrt-related-src/midl-3/troubleshooting.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/midl-3/troubleshooting.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment] 2019-10-10 22:46
Hi, @AliveDevil, thanks for reaching out with this question. For product support questions like this, you could try Microsoft Support, or developer feedback. I'll describe how to get to those resources.

You got here by clicking **Send feedback about** \> **This page**. If instead you click **Send feedback about** \> **This product**, then you'll be taken to the [Windows developer feedback](https://wpdev.uservoice.com) site (more info about that below).

Here are all of the developer support resources, for completeness.
- The [Windows developer feedback](https://wpdev.uservoice.com) site is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.

Thanks!
Steve

**Comment by stevewhims** [comment] 2019-11-04 23:18
I'll go ahead and close this issue now since there's no further action we can take here. Please reopen if I made a mistake in closing. ~Steve

**Comment by jehumb-havok** [comment] 2020-09-16 14:01
@stevewhims please reopen; the documentation is *very* light on this topic. This is not a support issue. @AliveDevil cannot possibly find an issue (and I can't either) since the documentation doesn't properly explain the usage of those keywords.

- if there is a limitation of using those with classes, as opposed to structs, which I believe is what the compiler might be trying to tell us, then this should be called out in the docs https://docs.microsoft.com/en-us/uwp/midl-3/intro#parameters
- for usage with arrays there is simply no explanation; in particular I believe the behavior is different from C# (the content of arrays without keyword can be modified because they are passed by reference by default, whereas in C++/WinRT they generate some `array_view<const T>` argument and therefore the content cannot be modified).
- the docs page linked to this issue should explain the error since the compiler error message is not detailed enough.

**Comment by stevewhims** [comment] 2020-09-17 02:30
Hi, @djee-ms, FYI I've pinged you an internal email, and copied in the feature team owner of MIDL 3.0,seeking clarification on what additional content we need to add here.

Let's track this via email, and we'll see what we can do.

Thanks!
Steve

**Comment by AliveDevil** [comment] 2020-10-06 12:45
So I just checked again to see what's up with it here. Given my ticket [here (#162)](162) it looks like `ref <Type> identifier` is the wrong syntax - correct is `ref const <Type> identifier`. Though in .NET Core 3.1 the projection is completely sideways (I do understand that .NET 5 going forward is dependent on CppWinRT/CsWinRT).
IDL:
```
struct Argument
{
	Int32 Parameter;
};

interface IHandler
{
	void Handle(ref const Argument arg);
};
```

But the projection into C# through the WinMD metadata creates this thing:
```
public interface IHandler
{
    void Handle(ref Argument arg);
}
```
This does not hold to `efficient input parameter passing`, as this allows overwriting the value that came in with something completely different, which is not what an `input parameter` is. `ref const` should've been translated into `in`-parameters.

Edit: Stupid me. German grammar and punctuation …

**Comment by stevewhims** [comment] 2020-10-06 22:56
Thanks, @AliveDevil, I'll ping the internal discussion that we have going by passing this info along.

**Comment by stevewhims** [comment] 2020-10-17 01:27
@AliveDevil, just a heads up that @djee-ms has updated a couple of topics with more info.

https://docs.microsoft.com/uwp/midl-3/intro#parameters
https://docs.microsoft.com/uwp/midl-3/troubleshooting

-Steve

**Comment by stevewhims** [comment] 2021-02-09 03:31
I'll go ahead and close this issue now that the info is now in the content.

Thanks again!
Steve

**Closed as completed by stevewhims** 2021-02-09 03:31 UTC
Labels: doc-bug, winrt-reference/tech, uwp/prod, Pri2
