### ISSUE TITLE
Updates on this page

### ISSUE THREAD

**Issue by MarcoEnxuto** [MicrosoftDocs/winrt-related#200] opened 2020-06-08 16:53 UTC
[Enter feedback here]
Hi, it's been a while. Are you expecting to update this page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64b487e4-704e-7407-dc4e-dbd4787b6b17
* Version Independent ID: b7c66d71-1e06-7758-ca85-1f7b62937025
* Content: [UWP features not yet supported on Xbox - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/extension-sdks/uwp-limitations-on-xbox#feedback)
* Content Source: [winrt-related-src/extension-sdks/uwp-limitations-on-xbox.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/extension-sdks/uwp-limitations-on-xbox.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment] 2020-06-08 22:52
Hi, @MarcoEnxuto, I'll go ahead and start investigating this question. I'll report progress here.

Thanks!
Steve

**Comment by stevewhims** [comment] 2020-06-25 19:14
I just sent a ping to the email thread I have going. No response yet, but I'll keep investigating.

**Comment by stevewhims** [comment] 2020-07-01 21:25
**UPDATE**: I've made contact with a feature team representative, who is looking into this. If the feature team have changes they'd like to make to this topic, then I'll make them. I'll also keep the internal discussion going periodically.

Thanks!
Steve

**Comment by stevewhims** [comment] 2020-07-08 02:44
I've sent another reminder internally. We're still investigating. Thanks for your patience.

-Steve

**Comment by MarcoEnxuto** [comment] 2020-07-20 12:13
So, any news? 🙂

**Comment by MarcoEnxuto** [comment] 2020-07-25 16:59
@stevewhims ?

**Comment by stevewhims** [comment] 2020-07-25 19:40
Hi, so I just sent a further reminder internally. It's possible that I might have to close this issue if I can't manage to get the info. In the meantime, just in case it's useful to you, here are all of the developer support resources, for completeness.

- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) is the right place to lobby for a change or a new feature, to make a suggestion, or to ask a product question.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

Thanks!
Steve

**Comment by stevewhims** [comment] 2020-07-28 22:13
Hi, @MarcoEnxuto, I've received confirmation that this topic is in fact still accurate. I'll go ahead and close the issue. Thanks for being patient!

-Steve

**Closed as completed by stevewhims** 2020-07-28 22:13 UTC
Labels: doc-bug, winrt-reference/tech, uwp/prod, Pri2
