### ISSUE TITLE
Specifying comments for Intellisense in .idl files

### ISSUE THREAD

**Issue by ChristopherLeaWacom** [MicrosoftDocs/winrt-related#127] opened 2019-06-05 15:12 UTC
I'm trying to export my .NET style comments to XML so they can be consumed by third party developers along with the resulting .winmd. Unfortunately it appears that .idl are either ignored entirely by Visual Studio or they're not properly supported.

If I place the documentation comments in the equivalent header they are indeed picked up and placed in the resulting .xml, but ofcourse the namespaces don't align with those used in the .winmd.

Am I doing something wrong or are they just not supported?

**Comment by ginami** [comment] 2019-06-06 15:22
Hi @ChristopherLeaWacom -- this list is for feedback on our docs. Can you give me a URL for a doc relevant to your questions? This will help me route your question to the correct author. Thanks!

**Comment by ChristopherLeaWacom** [comment] 2019-06-06 15:28
Apologies, I ended up here through lots of Googling and a similar issue posted here: https://github.com/MicrosoftDocs/winrt-related/issues/82.

Where else should I ask? I guess the fact there's no documentation about documentation is my issue, but it's hard to tell if it's even supported.

**Comment by stevewhims** [comment] 2019-06-07 20:21
Hi, @ChristopherLeaWacom, your instinct that this isn't supported is correct, and we apologize for the gap in the tooling. XML documentation (as described in https://docs.microsoft.com/dotnet/csharp/programming-guide/xmldoc/xml-documentation-comments), and [compiling with the /doc option](https://docs.microsoft.com/dotnet/csharp/language-reference/compiler-options/doc-compiler-option) is a solution for comments within .NET source code, but not for comments within an IDL file. The IDL comments are not processed even if you use /doc to compile C++/WinRT.

The only recourse currently (but it's manual, error-prone work), is to replicate the .idl content structure and copy-paste the comments. That would mimic the kind of .xml documentation file that's generated for C#. And then you'd see IntelliSense correctly light-up when ingesting, say, a NuGet package containing a C++/WinRT Component. Here's an example of how that'd look, IDL first and then .xml file.

```MIDL 3.0
namespace RuntimeComponent2
{
[default_interface]
/// <summary>
/// This class is a test class written in C++/WinRT
/// </summary>
runtimeclass Class
{
/// <summary>
/// This is the class constructor
/// </summary>
Class();
/// <summary>
/// This method does something new
/// </summary>
/// <returns>The result</returns>
Boolean DoSomething();
}
}
```

```xml
<?xml version="1.0"?>
<doc>
<assembly>
"RuntimeComponent2"
</assembly>
<members>
<member name="T:RuntimeComponent2.Class">
<summary>
This class is a test class written in C++/Winrt
</summary>
</member>
<member name="M:RuntimeComponent2.Class.#ctor">
<summary>
constructor of this class
</summary>
</member>
<member name="M:RuntimeComponent2.Class.DoSomething">
<summary>
This method does something new
</summary>
<returns>The result</returns>
</member>
</members>
</doc>
```

If you want to lobby for this feature, you could contact the
[Visual Studio User Voice](https://visualstudio.uservoice.com) feedback website, or the [Developer Community](https://developercommunity.visualstudio.com). Also, just FYI, for issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

I'll leave this open for a while; please close if you feel like it's resolved.

~Steve

**Comment by stevewhims** [comment] 2019-07-02 22:05
This issue feels as resolved as we can get it within this documentation-related feedback channel. So I'll go ahead and close it. Thanks! ~Steve

**Closed as completed by stevewhims** 2019-07-02 22:05 UTC
