### ISSUE TITLE
(Exception from HRESULT: 0x80070005 (E_ACCESSDENIED)) When trying to access an optical drive

### ISSUE THREAD

**Issue by lukeblevins** [MicrosoftDocs/winrt-related#141] opened 2019-09-24 01:47 UTC
Hello.
I've been trying very hard this evening to get my app to access my optical drive as a StorageFolder in order to retrieve its drive letter by GUID using AQS. It appears that the DeviceInformation object is found by the GUID, but attempting to access it with StorageDevice.FromId(device.Id).Path  results in an access denied exception. My manifest includes &lt;rescap:Capability Name="broadFileSystemAccess" /&gt; and &lt;DeviceCapability Name="optical" /&gt; but I'm still seeing this error. 
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a02a280f-6a8a-81c7-584f-7825c18272f9
* Version Independent ID: 2762cad0-c205-af68-7b19-e5f168af5358
* Content: [How to specify device capabilities in a package manifest - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/how-to-specify-device-capabilities-in-a-package-manifest)
* Content Source: [winrt-related-src/schemas/appxpackage/how-to-specify-device-capabilities-in-a-package-manifest.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/how-to-specify-device-capabilities-in-a-package-manifest.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by lukeblevins** [comment] 2019-09-24 01:51
```
<Capabilities>
    <uap:Capability Name="removableStorage" />
    <rescap:Capability Name="runFullTrust" />
    <rescap:Capability Name="broadFileSystemAccess" />
    <Capability Name="internetClient"/>
    <DeviceCapability Name="optical" />
</Capabilities>
```
```
     var opticalDrives = new List<string>();
     foreach(var device in (await Windows.Devices.Enumeration.DeviceInformation.FindAllAsync("System.Devices.ClassGuid:=\"{4d36e965-e325-11ce-bfc1-08002be10318}\"", null, Windows.Devices.Enumeration.DeviceInformationKind.Device)))
     {
           try
           {
               opticalDrives.Add(StorageDevice.FromId(device.Id).Path);
           }
           catch (KeyNotFoundException)
           {

           }
     }
```
By the way, I got the GUID filter from here: https://docs.microsoft.com/en-us/windows-hardware/drivers/install/system-defined-device-setup-classes-available-to-vendors

**Comment by lukeblevins** [comment] 2019-10-29 23:33
@laurenhughes Any update on this ticket?

**Comment by mijacobs** [comment] 2019-10-30 15:28
HI @duke7553; our apologies for the delayed response, this article wasn't assigned to the owner of this article.
 This feels not so much like feedback specifically about the documentation, but rather like a support request. Here are all of the developer support resources, for completeness.

- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
 - The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
 - The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
 - For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

 If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.

**Closed as completed** 2019-10-30 15:28 UTC
Labels: support-request
