### ISSUE TITLE
constexpr  is_guid_equal

### ISSUE THREAD

**Issue by DBJDBJ** [MicrosoftDocs/winrt-related#188] opened 2020-03-22 10:03 UTC
base.h around line 189

```cpp
    inline bool is_guid_equal(uint32_t const* const left, uint32_t const* const right) noexcept
    {
        return left[0] == right[0] && left[1] == right[1] && left[2] == right[2] && left[3] == right[3];
    }
```

It seems it could be easily `constexpr` ?

```cpp
    constexpr 
       inline bool is_guid_equal(uint32_t const* const left, uint32_t const* const right) noexcept
    {
        return left[0] == right[0] && left[1] == right[1] && left[2] == right[2] && left[3] == right[3];
    }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d36b3f5b-e729-300a-eb81-402648520ff3
* Version Independent ID: 40daa692-e9a1-2e27-0c10-c6baf69bc453
* Content: [winrt namespace (C++/WinRT) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/cpp-ref-for-winrt/winrt)
* Content Source: [winrt-related-src/cpp-ref-for-winrt/winrt.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/cpp-ref-for-winrt/winrt.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by DBJDBJ** [comment] 2020-03-22 10:11
After that is sorted `winrt::guid` should be easily tuned to fully `constexpr` too.

**Comment by stevewhims** [comment] 2020-03-23 06:14
Hi, @DBJDBJ, and thanks for filing this issue. The feedback channel you're using here (**Send feedback about** \> **This page**) is for feedback about the documentation itself. For example, if you believe that the content is incorrect, or that info needed to succeed with a common scenario is missing.

But for feedback about the product, like this, you can click **Send feedback about** \> **This product**, and you'll be taken to [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) (more info about that below).

Here are all of the developer support resources, for completeness.
- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

I'll go ahead and close this issue now, since there's no action I can take in the documentation. You can always reply to a closed issue, or even re-open it if you feel it's been closed in error.

-Steve

**Closed as completed by stevewhims** 2020-03-23 06:14 UTC
Labels: winrt-reference/tech, uwp/prod, Pri1

**Comment by DBJDBJ** [comment] 2020-03-23 15:00
@stevewhims 

I know but I could not find a right link to post this issue in a time I had. Can you please post the link here where one can comment on cppwinrt base.h contents?

**Comment by stevewhims** [comment] 2020-03-23 21:40
Hi, @DBJDBJ, try posting on StackOverflow, using the appropriate tag. If you follow this link, you'll see what the tag is: https://stackoverflow.com/questions/tagged/c%2b%2b-winrt.

-Steve
