### ISSUE TITLE
Questionable documentation on Package Extension uap8:dataprotection 

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/winrt-related#296] opened 2022-03-22 22:14 UTC
Looking at the updated documentation (Thank You!) https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap8-extension I immediately see some questionable items that either need to be reworked or better explained:

- The syntax of the child item is not proper XML Schema syntax, as in parentheses versus angle brackets.
- Appearing in the Executable and EntryPoint attributes description is this text: "If that EntryPoint property isn't specified, the EntryPoint defined for the app is used" As this is not under an Application element, it seems rather unclear what app could possibly be implied for the default.  I'm guessing these attributes might not be real???
- A whole slew of the attributes also appear to be more consistent to something under an Application element.  I wonder if this really belongs under an Application element (in which case some of the attributes like EntryPoint and StartPage should be taken from the Application element attributes instead of the Application Extension).

**Comment by drewbatgit** [comment] 2024-04-18 20:43
This appears to be a duplicate of https://github.com/MicrosoftDocs/winrt-related/issues/297.

**Closed as completed by drewbatgit** 2024-04-18 20:43 UTC
Labels: Pri3
