### ISSUE TITLE
Compsable class confusion

### ISSUE THREAD

**Issue by benstevens48** [MicrosoftDocs/winrt-related#140] opened 2019-09-13 17:21 UTC
I'm confused about this statement:

> Any runtime class that you define in the application that does derive from a base class is known as a composable class. And there are constraints around composable classes. For an application to pass the Windows App Certification Kit tests used by Visual Studio and by the Microsoft Store to validate submissions (and therefore for the application to be successfully ingested into the Microsoft Store), a composable class must ultimately derive from a Windows base class. Meaning that the class at the very root of the inheritance hierarchy must be a type originating in a Windows.* namespace.

Could I use `Windows.Foundation.IInspectable` as the base class? Would this be fine for submission to the Store? For example

```
unsealed runtimeclass Area : Windows.Foundation.IInspectable
{
    Area(Int32 width, Int32 height);
    Int32 Height;
    Int32 Width;
}

runtimeclass Volume : Area
{
    Volume(Int32 width, Int32 height, Int32 depth);
    Int32 Depth;
}
```

But in this case isn't that the same as 
```
unsealed runtimeclass Area
{
    Area(Int32 width, Int32 height);
    Int32 Height;
    Int32 Width;
}

runtimeclass Volume : Area
{
    Volume(Int32 width, Int32 height, Int32 depth);
    Int32 Depth;
}
```
(no explicit base class for `Area` implies an implicit base class of `Object`, which is the same as `Windows.Foundation.IInspectable`).

And so in that case I can't think of a situation where a class could ultimately derive from a type not in the `Windows.*` namespace. What is an example?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2dacbdf2-172f-dd41-829f-94295cd0c621
* Version Independent ID: b511accc-e0b1-9b30-d044-231d5204024d
* Content: [Introduction to Microsoft Interface Definition Language 3.0 - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/midl-3/intro#base-classes)
* Content Source: [winrt-related-src/midl-3/intro.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/midl-3/intro.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment] 2019-09-13 23:04
Hi, @benstevens48, remember that implementing an interface (such as Windows.Foundation.IInspectable, for example) is not the same as deriving from a bass (runtime) class. Implementing an interface is very common; more common I'd say than composing classes. Here's an example of composition.

Let's say that I author a **Shape** class. **Shape** doesn't derive from a bass class, so it's not composable. Then I derive a **Square** class from **Shape**. Consequently, **Square** is composable. With that situation as described, the Windows App Certification Kit (WACK tests will fail because **Shape** doesn't derive from a Windows.* runtime class. I can remedy that by deriving **Shape** from Windows.UI.Xaml.DependencyObject (for example). By so doing, I've made **Shape** itself composable, and composed from a Windows class. But I can't remedy the test failure by having **Shape** implement an interface. Having **Shape** implement interface(s) is my choice, but it's independent of the question of composability and WACK tests.

**Comment by benstevens48** [comment] 2019-09-14 05:49
Thanks for the reply. Is there a reason for the Windows.* requirement? It's tempting to find the simplest unsealed Windows class and derive from that, but I assume that's not sensible.

In fact I don't really want consumers of my class to derive from it, I just want to create a derived class in the implementation. I can use an interface in MIDL for this, but what is the recommended way to do this in the C++/WinRT implementation? Can I derive one implementation class from another? At the moment my implementation classes are thin wrappers around a normal C++ class where the inheritance occurs, but this is slightly inconvenient. I wasn't confident enough with C++/WinRT to try anything else. Is there as easier way (like listing an implementation class as a base class)?

**Comment by stevewhims** [comment] 2019-09-20 00:35
Re: the reason for the requirements, I'm not entirely sure, but I believe it's because the composable pattern was designed to meet the requirements of the Xaml UI platform, and it suffices for that (where everything is rooted in DependencyObject).

Your scenario is more advanced than the cases I've encountered and documented. So it might be a good idea to seek support/advice from the feature team, and you can find them monitoring questions here: https://stackoverflow.com/questions/tagged/c%2b%2b-winrt. But feel free to come back here any time, with updates or corrections that you feel need to be made to the docs. But, FWIW, it is possible to derive one implementation type from another. A special case of doing that is discussed here: https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/author-apis#deriving-from-a-type-that-has-a-non-default-constructor

Sorry I can't offer more direct help with your scenario here.

~Steve

**Comment by stevewhims** [comment] 2019-09-25 22:16
I'll go ahead and close this issue now, since it seems resolved. But please reactivate it if you feel like I've closed it in error. Thanks! ~Steve

**Closed as completed by stevewhims** 2019-09-25 22:16 UTC
Labels: product-question, forum

**Comment by benstevens48** [comment] 2019-09-26 18:25
Thanks for the reply. I'll try to find out more on the forum when I have time.
