### ISSUE TITLE
Broken hierarchy

### ISSUE THREAD

**Issue by zyndor** [MicrosoftDocs/winrt-related#271] opened 2021-09-10 09:57 UTC
This element has a similarly named parent in the documentation (which cannot be selected), with a number of other child elements. This wrongly suggests that those would be child elements of uap5:DriverConstraing in the AppxManifest (though their documentation clarifies this).

Most likely an error with the generation of the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0881854-5205-32f9-d4fe-31eb15bc4777
* Version Independent ID: 2b0461d9-168b-8208-2ae3-bb9fe8349f33
* Content: [uap5:DriverConstraint - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap5-driverconstraint)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap5-DriverConstraint.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap5-DriverConstraint.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment] 2021-09-10 14:36
Thanks for following up with us. I took a look at the [uap5:DriverConstraint](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap5-driverconstraint) article and I'm not seeing the issue you're reporting. The link to the parent uap5:DriverDependency element in the "Element hierarchy" section works, and I'm not seeing any other elements named "DriverConstraint" in the docs.

Can you please provide more details to clarify the issue you're seeing?

**Comment by drewbatgit** [comment] 2021-10-06 20:38
@zyndor Can you provide more information about the issue you're seeing? Can you provide the name of the "similarly named element"? Thanks!

**Comment by drewbatgit** [comment] 2021-12-10 21:32
@zyndor I can't reproduce this error so I'm going to close this issue. If you still see the issue on your end, you can still respond to this github issue or create a new one. Thanks!

**Closed as completed by drewbatgit** 2021-12-10 21:32 UTC
Labels: winrt-reference/tech, uwp/prod, Pri2
